<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ipc\\carskills\\adapters\\glassrooflidapi' => '/infrastructure/adapters/GlassRoofLidApi.php',
                'ipc\\carskills\\adapters\\parkedapi' => '/infrastructure/adapters/ParkedApi.php',
                'ipc\\carskills\\carisparkedapi' => '/domain/CarIsParkedApi.php',
                'ipc\\carskills\\carskill' => '/domain/CarSkill.php',
                'ipc\\carskills\\closethelidcarskill' => '/domain/CloseTheLidCarSkill.php',
                'ipc\\carskills\\lazydeveloperexception' => '/domain/LazyDeveloperException.php',
                'ipc\\carskills\\lidapi' => '/domain/LidApi.php',
                'stefanscarvendor\\familycarseries\\carvendorapi' => '/infrastructure/CarVendorApi.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
